/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionPopup: typeof import('./src/components/ActionPopup.vue')['default']
    ActionSheet: typeof import('./src/components/ActionSheet.vue')['default']
    AvatarBox: typeof import('./src/components/customSelectPerson/AvatarBox.vue')['default']
    CommonTable: typeof import('./src/components/CommonTable.vue')['default']
    CustomCheckBox: typeof import('./src/components/CustomCheckBox.vue')['default']
    CustomSelectPerson: typeof import('./src/components/customSelectPerson/index.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    DialogComponent: typeof import('./src/components/DialogComponent.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    IconWrapper: typeof import('./src/components/IconWrapper.vue')['default']
    InfiniteList: typeof import('./src/components/InfiniteList.vue')['default']
    PopMenu: typeof import('./src/components/PopMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    SortPopup: typeof import('./src/components/SortPopup.vue')['default']
    StackIcon: typeof import('./src/components/StackIcon.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSwitch: typeof import('vant/es')['Switch']
    VanToast: typeof import('vant/es')['Toast']
    VanUploader: typeof import('vant/es')['Uploader']
  }
  export interface GlobalDirectives {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
